In [1]:
import string
import pandas as pd 
import numpy as np 
import nltk

In [2]:
from nltk.corpus import stopwords
filters = set(stopwords.words("english") + list(string.punctuation))

In [9]:
from nltk.tokenize import word_tokenize


def remove_stop_words(data):
    word_list = word_tokenize(data)
    result = [ word.lower() for word in word_list if word.lower() not in filters]
    print(word_list)
    return " ".join(result)

In [14]:
data = ["    Hello  World! is this dream    ?    ", "   !@#$% This is an test Subject: :   :"]
df = pd.DataFrame(data, columns=["tags"])
df

                                       tags
0      Hello  World! is this dream    ?
1      !@#$% This is an test Subject: :   :

In [15]:
df["preprocessed"] = df["tags"].apply(remove_stop_words)
df

['Hello', 'World', '!', 'is', 'this', 'dream', '?']
['!', '@', '#', '$', '%', 'This', 'is', 'an', 'test', 'Subject', ':', ':', ':']

                                       tags       preprocessed
0      Hello  World! is this dream    ?      hello world dream
1      !@#$% This is an test Subject: :   :       test subject

In [12]:
remove_stop_words("!@#$% This is an test Subject:::")

['!', '@', '#', '$', '%', 'This', 'is', 'an', 'test', 'Subject', ':', ':', ':']

'test subject'

# Gradient Descent implementation using only math

In [9]:
# Given : y_hat  = wx+b
#Loss : L = (y-y_hat)^2

x = 6
y = 12
w = 2
b = 1
lr = 0.0001

length = 10
#implement simple Linear regression model 

def graident_descent(x,y,w,b,lr):
    predicted = w*x+b
    new_w = (-2 * (y - predicted)) * x 
    new_b = -2 * (y - predicted)
    w = w-(lr * new_w)
    b = b-(lr * new_b)
    return w,b
for epoch in range(length):
    w,b = graident_descent(x,y,w,b,lr)
    print(w,b)

1.9988 0.9998
1.9976088799999998 0.99960148
1.9964265742879999 0.9994044290480001
1.9952530176382686 0.9992088362730449
1.9940881453077455 0.9990146908846244
1.9929318930324682 0.9988219821720782
1.991784197024028 0.9986306995040048
1.9906449939660502 0.9984408323276752
1.9895142210107015 0.9982523701684505
1.9883918157752223 0.9980653026292039

In [11]:
print(1.988 *6+0.998)

12.926

In [9]:
import pandas  as pd
data = [
    {'customer_id': 'C1', 'amount': 100, 'date': '2024-01-01'},
    {'customer_id': 'C2', 'amount': 50, 'date': '2024-01-02'},
    {'customer_id': 'C1', 'amount': 150, 'date': '2024-01-03'},
    {'customer_id': 'C1', 'amount': 75, 'date': '2024-01-05'}
]

df = pd.DataFrame(data, columns=["customer_id", "amount","date"])
df

  customer_id  amount        date
0          C1     100  2024-01-01
1          C2      50  2024-01-02
2          C1     150  2024-01-03
3          C1      75  2024-01-05

In [10]:
df["num_transaction"] = df.groupby("customer_id")["date"].transform("count")
df["sum_amount"] = df.groupby("customer_id")["amount"].transform("sum")
df["avg_transaction"] = round(df["sum_amount"]/df["num_transaction"],2)
df

,customer_id,amount,date,num_transaction,sum_amount,avg_transaction
0,C1,100,2024-01-01,3,325,108.33
1,C2,50,2024-01-02,1,50,50.00
2,C1,150,2024-01-03,3,325,108.33
3,C1,75,2024-01-05,3,325,108.33

In [11]:
df["date"] = pd.to_datetime(df["date"])
df

  customer_id  amount       date  num_transaction  sum_amount  avg_transaction
0          C1     100 2024-01-01                3         325           108.33
1          C2      50 2024-01-02                1          50            50.00
2          C1     150 2024-01-03                3         325           108.33
3          C1      75 2024-01-05                3         325           108.33

In [12]:
df["first_transaction"] = df.groupby("customer_id")["date"].transform("min")
df["last_transaction"] = df.groupby("customer_id")["date"].transform("max")
df

,customer_id,amount,date,num_transaction,sum_amount,avg_transaction,first_transaction,last_transaction
0,C1,100,2024-01-01,3,325,108.33,2024-01-01,2024-01-05
1,C2,50,2024-01-02,1,50,50.00,2024-01-02,2024-01-02
2,C1,150,2024-01-03,3,325,108.33,2024-01-01,2024-01-05
3,C1,75,2024-01-05,3,325,108.33,2024-01-01,2024-01-05

In [18]:
result = df.drop(columns=["amount","date"])
result = result.drop_duplicates()
result

,customer_id,num_transaction,sum_amount,avg_transaction,first_transaction,last_transaction
0,C1,3,325,108.33,2024-01-01,2024-01-05
1,C2,1,50,50.00,2024-01-02,2024-01-02

In [5]:
def find_sum_index(arr, target):
    result = []
    for indx, val in enumerate(arr):
        diff = target - val 
        if (diff in arr ) and (diff != val):
            result.append(indx)
    return result

In [21]:
print(find_sum_index([2, 7, 11, 15],9))

[0, 1]

In [7]:
def find_duplicates(arr):
    dec = set()
    duplicate = []
    for i in arr:
        if i not in dec:
            dec.add(i)
        else:
            duplicate.append(i)
    return duplicate

In [8]:
print(find_duplicates([1, 2, 3, 2, 4, 5, 3]))

[2, 3]

In [19]:
def find_moving_avg(arr, k):
    result= []
    l = 0
    while (l+k) <= len(arr):
        val = sum(arr[l:l+k])
        result.append(val/k)
        l+=1
    return result

In [20]:
print(find_moving_avg([1, 3, 2, 6, -1, 4, 1, 8, 2],5))

[2.2, 2.8, 2.4, 3.6, 2.8]

In [30]:
import pandas as pd 
df = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Alice', 'Bob', 'Carol', 'David'],
    'salary': [50000, 60000, 55000, 65000, 58000],
    'department': ['IT', 'HR', 'IT', 'Finance', 'HR']
})
df

   employee_id   name  salary department
0            1   John   50000         IT
1            2  Alice   60000         HR
2            3    Bob   55000         IT
3            4  Carol   65000    Finance
4            5  David   58000         HR

In [31]:
df[df["salary"]> 55000]

   employee_id   name  salary department
1            2  Alice   60000         HR
3            4  Carol   65000    Finance
4            5  David   58000         HR

In [32]:
result = df.groupby("department").agg({
    "salary" : ["mean", "sum"]
}).reset_index()
result.columns = ["department", "avg_salary","total_salary"]
result
df = df.merge(result , left_on= "department", right_on="department")
df

   employee_id   name  salary department  avg_salary  total_salary
0            1   John   50000         IT     52500.0        105000
1            2  Alice   60000         HR     59000.0        118000
2            3    Bob   55000         IT     52500.0        105000
3            4  Carol   65000    Finance     65000.0         65000
4            5  David   58000         HR     59000.0        118000

In [33]:
df["salary_rank"] = df["salary"].rank()
df.sort_values(by="salary_rank", ascending=True)

,employee_id,name,salary,department,avg_salary,total_salary,salary_rank
0,1,John,50000,IT,52500.0,105000,1.0
2,3,Bob,55000,IT,52500.0,105000,2.0
4,5,David,58000,HR,59000.0,118000,3.0
1,2,Alice,60000,HR,59000.0,118000,4.0
3,4,Carol,65000,Finance,65000.0,65000,5.0

In [37]:
df[df["total_salary"] == max(df["total_salary"])]["department"]

1    HR
4    HR
Name: department, dtype: object

In [46]:

def find_anagram(arr):
    dec = {}
    for word in arr:
        p_word = tuple(sorted(word))
        if p_word not in dec :
            dec[p_word] = [word]
        else :
            dec[p_word].append(word)
    return list(dec.values())

In [47]:
print(find_anagram(["eat","tea","tan","ate","nat","bat"]))

[['eat', 'tea', 'ate'], ['tan', 'nat'], ['bat']]

In [58]:
def longest_sequence(word):
    result= []
    seen = []
    temp = ""
    for letter in word :
        if letter not in seen :
            seen.append(letter)
            temp+=letter
        else :
            result.append(temp)
            temp = ""
            temp +=letter
    print(result)
    return max(result)

In [60]:
print(longest_sequence("dvdf"))

['dv']
dv

In [62]:
import numpy as np 
transactions = pd.DataFrame({
    'customer_id': np.random.randint(1, 50, 500),
    'transaction_date': pd.date_range('2023-01-01', periods=500, freq='D'),
    'amount': np.random.randint(10, 500, 500)
})
transactions.head()

   customer_id transaction_date  amount
0           22       2023-01-01     377
1           40       2023-01-02     128
2            9       2023-01-03     296
3           17       2023-01-04     375
4            7       2023-01-05      39

In [64]:
print(max(transactions["transaction_date"]) - min(transactions["transaction_date"]) )

499 days 00:00:00

In [68]:
result = transactions.groupby("customer_id")["transaction_date"].max().reset_index()
result.columns = ["customer_id","last_purchase_date"]

In [69]:
transactions = transactions.merge( result, left_on= "customer_id", right_on="customer_id")
transactions.head()

   customer_id transaction_date  amount last_purchase_date
0           22       2023-01-01     377         2024-05-09
1           40       2023-01-02     128         2024-05-07
2            9       2023-01-03     296         2024-05-12
3           17       2023-01-04     375         2024-04-09
4            7       2023-01-05      39         2024-05-05

In [70]:
len(transactions)

500

In [94]:
total_purchase = transactions.groupby("customer_id").agg({
    "amount" : ["sum"],
    "transaction_date" : ["count"]
}).reset_index()

total_purchase.columns = ["customer_id", "Monetary", "Frequency"]
total_purchase.head()

   customer_id  Monetary  Frequency
0            1      3181         11
1            2      1944          8
2            3      2275          8
3            4      3416         14
4            5      1924          6

In [95]:
df = transactions[["customer_id","last_purchase_date"]]
df.head()

   customer_id last_purchase_date
0           22         2024-05-09
1           40         2024-05-07
2            9         2024-05-12
3           17         2024-04-09
4            7         2024-05-05

In [96]:
df = df.merge(total_purchase, left_on= "customer_id", right_on= "customer_id")
df.head()

   customer_id last_purchase_date  Monetary  Frequency
0           22         2024-05-09      1817          8
1           40         2024-05-07      2016         10
2            9         2024-05-12      3809         14
3           17         2024-04-09      3516         13
4            7         2024-05-05      2459         13

In [97]:
df = df.drop_duplicates()
print(len(df))
df.head()

49

   customer_id last_purchase_date  Monetary  Frequency
0           22         2024-05-09      1817          8
1           40         2024-05-07      2016         10
2            9         2024-05-12      3809         14
3           17         2024-04-09      3516         13
4            7         2024-05-05      2459         13

In [98]:
def get_days(data):
    return (data - pd.Timestamp( "2024-01-01" )).days

print(get_days(df["last_purchase_date"].iloc[0]))

129

In [99]:
df["Regency"] = df["last_purchase_date"].apply(get_days)

In [103]:
df.sort_values(by="customer_id", ascending= True)[:10]

     customer_id last_purchase_date  Monetary  Frequency  Regency
23             1         2024-03-05      3181         11       64
55             2         2024-05-04      1944          8      124
12             3         2024-01-16      2275          8       15
16             4         2024-03-25      3416         14       84
121            5         2024-05-13      1924          6      133
94             6         2024-05-14      1852          9      134
4              7         2024-05-05      2459         13      125
20             8         2024-04-05      2406         11       95
2              9         2024-05-12      3809         14      132
19            10         2024-05-06      3106         13      126

In [104]:
min(df["Regency"])

-141

In [107]:
def give_score(data):
    avg = df["Regency"].mean()
    if data < avg :
        val =  np.random.randint(4,5, 1)
        return val[0]
    else :
        val = np.random.randint(1,3,1)
        return val[0]

In [113]:
df["r_Score"] = pd.qcut(
    df["Regency"],
    q = 5,
    labels=["5", "4", "3", "2", "1"]
)
df.head()

,customer_id,last_purchase_date,Monetary,Frequency,Regency,f_Score,r_Score
0,22,2024-05-09,1817,8,129,1,1
1,40,2024-05-07,2016,10,127,2,1
2,9,2024-05-12,3809,14,132,1,1
3,17,2024-04-09,3516,13,99,1,3
4,7,2024-05-05,2459,13,125,2,1

In [114]:
df["f_Score"] = pd.qcut(
    df["Frequency"],
    q = 5 ,
    labels=["1", "2", "3", "4", "5"]
)
df.head()

,customer_id,last_purchase_date,Monetary,Frequency,Regency,f_Score,r_Score
0,22,2024-05-09,1817,8,129,2,1
1,40,2024-05-07,2016,10,127,3,1
2,9,2024-05-12,3809,14,132,5,1
3,17,2024-04-09,3516,13,99,4,3
4,7,2024-05-05,2459,13,125,4,1

In [115]:
df["m_Score"] = pd.qcut(
    df["Monetary"],
    q = 5 ,
    labels=["1", "2", "3", "4", "5"]
)
df.head()

,customer_id,last_purchase_date,Monetary,Frequency,Regency,f_Score,r_Score,m_Score
0,22,2024-05-09,1817,8,129,2,1,1
1,40,2024-05-07,2016,10,127,3,1,2
2,9,2024-05-12,3809,14,132,5,1,5
3,17,2024-04-09,3516,13,99,4,3,5
4,7,2024-05-05,2459,13,125,4,1,3

In [139]:
def give_segemant(customer):
    row = df.loc[df["customer_id"] == customer].iloc[0]

    r = row["r_Score"]
    f = row["f_Score"]
    m = row["m_Score"]

    if r in ["5", "4"] and f in ["5", "4"] and m in ["5", "4"]:
        return "Champion"
    elif f in ["5", "4"] and  r in ["3", "2", "1"] and m in ["1","2","3"] :
        return "Loyal"
    elif f in ["5", "4"] and m in ["5", "4"] and r in ["1","2","3"] :
        return "High Risk"
    else:
        return "Lost"

print(give_segemant(1))

Lost

In [142]:
df["Segement"] = df["customer_id"].apply(give_segemant)
df.head()

,customer_id,last_purchase_date,Monetary,Frequency,Regency,f_Score,r_Score,m_Score,Segement
0,22,2024-05-09,1817,8,129,2,1,1,Lost
1,40,2024-05-07,2016,10,127,3,1,2,Lost
2,9,2024-05-12,3809,14,132,5,1,5,High Risk
3,17,2024-04-09,3516,13,99,4,3,5,High Risk
4,7,2024-05-05,2459,13,125,4,1,3,Loyal

In [143]:
df[["customer_id","Monetary","Frequency","Regency","f_Score","r_Score","m_Score","Segement"]]

,customer_id,Monetary,Frequency,Regency,f_Score,r_Score,m_Score,Segement
0,22,1817,8,129,2,1,1,Lost
1,40,2016,10,127,3,1,2,Lost
2,9,3809,14,132,5,1,5,High Risk
3,17,3516,13,99,4,3,5,High Risk
4,7,2459,13,125,4,1,3,Loyal
5,31,3370,11,102,3,3,5,Lost
6,11,3012,10,88,3,4,4,Lost
7,36,1602,7,81,1,4,1,Lost
8,37,3347,13,78,4,4,4,Champion
9,13,1965,11,7,3,5,2,Lost
10,46,3045,15,113,5,2,4,High Risk
11,41,2954,14,53,5,4,4,Champion
12,3,2275,8,15,2,5,3,Lost
13,49,4185,15,79,5,4,5,Champion
15,12,2150,11,70,3,4,2,Lost
16,4,3416,14,84,5,4,5,Champion
19,10,3106,13,126,4,1,4,High Risk
20,8,2406,11,95,3,3,3,Lost
21,23,2275,9,120,2,2,3,Lost
22,35,1201,6,119,1,2,1,Lost
23,1,3181,11,64,3,4,4,Lost
24,43,1805,6,96,1,3,1,Lost
28,39,3846,14,122,5,2,5,High Risk
29,25,3059,11,110,3,2,4,Lost
31,32,2390,8,77,2,4,3,Lost
35,44,3730,16,118,5,2,5,High Risk
36,24,1561,9,128,2,1,1,Lost
37,14,1624,5,-141,1,5,1,Lost
38,15,3583,12,86,4,4,5,Champion
40,30,3118,11,33,3,5,4,Lost
42,38,4250,16,107,5,3,5,High Risk
43,42,1966,7,-41,1,5,2,Lost
44,21,1869,7,-49,1,5,1,Lost
46,29,3412,13,130,4,1,5,High Risk
50,26,2915,11,92,3,3,4,Lost
55,2,1944,8,124,2,2,2,Lost
57,19,2713,9,117,2,2,3,Lost
59,20,1970,11,131,3,1,2,Lost
61,47,2304,11,101,3,3,3,Lost
65,27,1928,7,48,1,5,2,Lost
66,28,2404,10,0,3,5,3,Lost
70,16,2984,10,97,3,3,4,Lost
74,33,1949,7,-20,1,5,2,Lost
91,48,1888,7,105,1,3,1,Lost
94,6,1852,9,134,2,1,1,Lost
108,18,1196,7,108,1,2,1,Lost
110,45,2267,7,22,1,5,3,Lost
113,34,1957,8,114,2,2,2,Lost
121,5,1924,6,133,1,1,2,Lost

In [141]:
df["Segement"].value_counts()

Segement
Lost         35
High Risk     8
Champion      5
Loyal         1
Name: count, dtype: int64

In [1]:
import pandas as pd 
left = [{"id": 1, "name": "Alice"}, {"id": 2, "name": "Bob"}]
right = [{"id": 1, "score": 95}, {"id": 3, "score": 88}]
left = pd.DataFrame(left, columns=["id", "name"])
right = pd.DataFrame(right, columns=["id","score"])

df = left.merge(right , left_on= "id", right_on= "id", how="outer")
df

   id   name  score
0   1  Alice   95.0
1   2    Bob    NaN
2   3    NaN   88.0

In [3]:
df = [
  {"user_id": 1, "group": "control", "converted": True},
  {"user_id": 2, "group": "treatment", "converted": True},
  {"user_id": 3, "group": "control", "converted": False},
  {"user_id": 4, "group": "treatment", "converted": True}
]

df = pd.DataFrame(df, columns=["user_id", "group","converted"])
df.head()

   user_id      group  converted
0        1    control       True
1        2  treatment       True
2        3    control      False
3        4  treatment       True

In [4]:
conversion_Rate = df.groupby("group").agg({
    "user_id" : ["count"],
    "converted" : ["sum"]
}).reset_index()

conversion_Rate.columns = ["group", "user_id_cnt","converted_sum"]
conversion_Rate

       group  user_id_cnt  converted_sum
0    control            2              1
1  treatment            2              2

In [5]:
conversion_Rate["conversion_rate"] = round(conversion_Rate["converted_sum"]/conversion_Rate["user_id_cnt"],2)
conversion_Rate

       group  user_id_cnt  converted_sum  conversion_rate
0    control            2              1              0.5
1  treatment            2              2              1.0

In [6]:
data = [
  {"user_id": 1, "group": "control", "converted": True},
  {"user_id": 2, "group": "treatment", "converted": True},
  {"user_id": 3, "group": "control", "converted": False},
  {"user_id": 4, "group": "treatment", "converted": True}
]

In [19]:
def find_conversin_rate(data):
    dec = {}
    result = {}
    for user in data:
        if user["group"] not in dec:
            dec[ user["group"] ] = {}
            dec[ user["group"] ]["user_cnt"] = 1
            dec[ user["group"] ]["converted"] = int(user["converted"])
        else :
            dec[ user["group"] ]["converted"] += int(user["converted"])
            dec[ user["group"] ]["user_cnt"] += 1

    for key,value in dec.items():
        result[key] = {}
        result[key]["conversion_rate"] =  value["converted"]/value["user_cnt"]
    return result

In [20]:
print(find_conversin_rate(data))

{'control': {'conversion_rate': 0.5}, 'treatment': {'conversion_rate': 1.0}}