In [24]:
import pandas as pd

In [25]:
arr = [1, 2, None, 4, None, 6]

df = pd.DataFrame(arr, columns=["list"])
df

   list
0   1.0
1   2.0
2   NaN
3   4.0
4   NaN
5   6.0

In [26]:
avg = df["list"].mean()
df["list"] = df["list"].fillna(avg)
df["list"] = df["list"].round(2)
df

   list
0  1.00
1  2.00
2  3.25
3  4.00
4  3.25
5  6.00

In [27]:
array = df.to_numpy()

In [28]:
array

array([[1.  ],
       [2.  ],
       [3.25],
       [4.  ],
       [3.25],
       [6.  ]])

In [29]:
from sklearn.preprocessing import minmax_scale
import numpy as np 
input_arry = np.array([10,20,30,40,50])

mx = minmax_scale(X=input_arry)
mx

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [30]:
z_score = []

z_score.append((input_arry-input_arry.mean())/input_arry.std())
z_score

[array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])]

In [31]:
from scipy.stats import zscore

z = zscore(input_arry)

z

array([-1.41421356, -0.70710678,  0.        ,  0.70710678,  1.41421356])

In [32]:
def moving_window(arr, window):
    df = pd.DataFrame(arr, columns=["list"])
    result = df["list"].rolling(window=window,min_periods=1).mean()
    return result

In [33]:
moving_window([1, 3, 5, 7, 9], 3)

0    1.0
1    2.0
2    3.0
3    5.0
4    7.0
Name: list, dtype: float64

In [34]:
Input= [
  "2024-01-01 10:00:00 INFO User logged in",
  "2024-01-01 10:05:00 ERROR Connection failed",
  "2024-01-01 10:03:00 ERROR Timeout"
] # type: ignore

df = pd.DataFrame(Input, columns=["logs"])
df

                                          logs
0      2024-01-01 10:00:00 INFO User logged in
1  2024-01-01 10:05:00 ERROR Connection failed
2            2024-01-01 10:03:00 ERROR Timeout

In [35]:
def solve(data):
    strings = data.split(" ")
    if strings[2] == "ERROR":
        return strings[1]
    return None

In [36]:
df["Error_Found"] = df["logs"].apply(solve)
df

                                          logs Error_Found
0      2024-01-01 10:00:00 INFO User logged in        None
1  2024-01-01 10:05:00 ERROR Connection failed    10:05:00
2            2024-01-01 10:03:00 ERROR Timeout    10:03:00

In [37]:
df["Error_Found"] = pd.to_datetime(
    df["Error_Found"], format="%H:%M:%S", errors="coerce"
).dt.time

In [38]:
df = df[df["Error_Found"]!=None]
df.sort_values(by="Error_Found",ascending= True)

                                          logs Error_Found
2            2024-01-01 10:03:00 ERROR Timeout    10:03:00
1  2024-01-01 10:05:00 ERROR Connection failed    10:05:00
0      2024-01-01 10:00:00 INFO User logged in         NaT

In [39]:
from nltk.corpus import stopwords
arr = ["  Hello, World!  ", "This is a TEST!!!"]
df = pd.DataFrame(arr, columns=["Words"])
df

               Words
0    Hello, World!
1  This is a TEST!!!

In [40]:
import string
from nltk.tokenize import word_tokenize
combined_filter = set(stopwords.words("english") + list(string.punctuation))

In [41]:
def remove_stop_words(data):
    tokenize = word_tokenize(data)
    filtered = [ w.lower() for w in tokenize if w.lower() not in combined_filter ]
    return " ".join(filtered)

In [42]:
df["stop_words_removed"] = df["Words"].apply(remove_stop_words)

In [43]:
df

               Words stop_words_removed
0    Hello, World!          hello world
1  This is a TEST!!!               test

In [44]:
import re
def feature_extraction(link):
    till_endpoint = link.split("/")
    after_endpoint = re.split(r"[^\w]+",till_endpoint[-1])
    dec = {}
    dec["domain"] = till_endpoint[2]
    dec["path"]  = "/"+after_endpoint[0]
    dec["Params"] = {}
    dec["Params"][after_endpoint[1]] = after_endpoint[2]
    dec["Params"][after_endpoint[3]] = after_endpoint[-1]
    return dec

In [45]:
data = {
    "text": [
        "https://shop.com/items?id=456&category=clothing",
        "https://example.org/search?id=789&category=books",
        "https://store.net/products?id=101&category=home",
        "https://mysite.com/listing?id=202&category=fitness",
        "https://demo.io/catalog?id=303&category=beauty",
        "https://marketplace.com/product?id=404&category=toys",
        "https://ecommerce.org/items?id=505&category=grocery",
        "https://webshop.net/products?id=606&category=automotive",
        "https://portal.com/view?id=707&category=furniture",
        "https://online-store.io/product?id=808&category=gaming"
    ]
}

text_data = pd.DataFrame(data)
text_data

                                                text
0    https://shop.com/items?id=456&category=clothing
1   https://example.org/search?id=789&category=books
2    https://store.net/products?id=101&category=home
3  https://mysite.com/listing?id=202&category=fit...
4     https://demo.io/catalog?id=303&category=beauty
5  https://marketplace.com/product?id=404&categor...
6  https://ecommerce.org/items?id=505&category=gr...
7  https://webshop.net/products?id=606&category=a...
8  https://portal.com/view?id=707&category=furniture
9  https://online-store.io/product?id=808&categor...

In [46]:
text_data["extracted_features"] = text_data["text"].apply(feature_extraction)
text_data

,text,extracted_features
0,https://shop.com/items?id=456&category=clothing,"{'domain': 'shop.com', 'path': '/items', 'Para..."
1,https://example.org/search?id=789&category=books,"{'domain': 'example.org', 'path': '/search', '..."
2,https://store.net/products?id=101&category=home,"{'domain': 'store.net', 'path': '/products', '..."
3,https://mysite.com/listing?id=202&category=fit...,"{'domain': 'mysite.com', 'path': '/listing', '..."
4,https://demo.io/catalog?id=303&category=beauty,"{'domain': 'demo.io', 'path': '/catalog', 'Par..."
5,https://marketplace.com/product?id=404&categor...,"{'domain': 'marketplace.com', 'path': '/produc..."
6,https://ecommerce.org/items?id=505&category=gr...,"{'domain': 'ecommerce.org', 'path': '/items', ..."
7,https://webshop.net/products?id=606&category=a...,"{'domain': 'webshop.net', 'path': '/products',..."
8,https://portal.com/view?id=707&category=furniture,"{'domain': 'portal.com', 'path': '/view', 'Par..."
9,https://online-store.io/product?id=808&categor...,"{'domain': 'online-store.io', 'path': '/produc..."

In [47]:
pd.set_option("display.max_columns",None)
print(text_data["extracted_features"][2:3])

2    {'domain': 'store.net', 'path': '/products', '...
Name: extracted_features, dtype: object

In [48]:
dic_Data = [
  {"customer_id": 1, "amount": 100},
  {"customer_id": 2, "amount": 50},
  {"customer_id": 1, "amount": 75}
]

data_df = pd.DataFrame(dic_Data, columns=["customer_id", "amount"])
data_df

   customer_id  amount
0            1     100
1            2      50
2            1      75

In [49]:
result = data_df.groupby("customer_id")["amount"].sum().reset_index()
result

   customer_id  amount
0            1     175
1            2      50

In [50]:

raw_data = """Red, Mr. Owen Harris
Pink, Mrs. John Bradley (Florence Briggs Thayer)
Yellow, Miss. Laina
Red, Mrs. Jacques Heath (Lily May Peel)
Red, Mr. William Henry
Yellow, Mr. James
Mr. Timothy J
Yellow, Master. Gosta Leonard
White, Mrs. Oscar W (Elisabeth Vilhelmina Berg)
Yellow, Mrs. Nicholas (Adele Achem)
Green, Miss. Marguerite Rut
Miss. Elizabeth
Yellow, Mr. William Henry
Yellow, Mr. Anders Johan
Yellow, Miss. Hulda Amanda Adolfina
Yellow, Mrs. (Mary D Kingcome)
Pink, Master. Eugene
Red, Mr. Charles Eugene
Green, Mrs. Julius (Emelia Maria Vandemoortele)
Red, Mrs. Fatima
Red, Mr. Joseph J
Green, Mr. Lawrence
Red, Miss. Anna "Annie"
Red, Mr. William Thompson
Green, Miss. Torborg Danira
Red, Mrs. Carl Oscar (Selma Augusta Emilia Johansson)
Green, Mr. Farred Chehab
Red, Mr. Charles Alexander
White, Miss. Ellen "Nellie"
Green, Mr. Lalio
Red, Don. Manuel E
Yellow, Mrs. William Augustus (Marie Eugenie)
Green, Miss. Mary Agatha
Red, Mr. Edward H
Red, Mr. Edgar Joseph"""


result =[]
data = raw_data.split("\n")
for line in data:
    result.append(line.split(","))
result

[['Red', ' Mr. Owen Harris'],
 ['Pink', ' Mrs. John Bradley (Florence Briggs Thayer)'],
 ['Yellow', ' Miss. Laina'],
 ['Red', ' Mrs. Jacques Heath (Lily May Peel)'],
 ['Red', ' Mr. William Henry'],
 ['Yellow', ' Mr. James'],
 ['Mr. Timothy J'],
 ['Yellow', ' Master. Gosta Leonard'],
 ['White', ' Mrs. Oscar W (Elisabeth Vilhelmina Berg)'],
 ['Yellow', ' Mrs. Nicholas (Adele Achem)'],
 ['Green', ' Miss. Marguerite Rut'],
 ['Miss. Elizabeth'],
 ['Yellow', ' Mr. William Henry'],
 ['Yellow', ' Mr. Anders Johan'],
 ['Yellow', ' Miss. Hulda Amanda Adolfina'],
 ['Yellow', ' Mrs. (Mary D Kingcome)'],
 ['Pink', ' Master. Eugene'],
 ['Red', ' Mr. Charles Eugene'],
 ['Green', ' Mrs. Julius (Emelia Maria Vandemoortele)'],
 ['Red', ' Mrs. Fatima'],
 ['Red', ' Mr. Joseph J'],
 ['Green', ' Mr. Lawrence'],
 ['Red', ' Miss. Anna "Annie"'],
 ['Red', ' Mr. William Thompson'],
 ['Green', ' Miss. Torborg Danira'],
 ['Red', ' Mrs. Carl Oscar (Selma Augusta Emilia Johansson)'],
 ['Green', ' Mr. Farred Chehab'],
 ['Red', ' Mr. Charles Alexander'],
 ['White', ' Miss. Ellen "Nellie"'],
 ['Green', ' Mr. Lalio'],
 ['Red', ' Don. Manuel E'],
 ['Yellow', ' Mrs. William Augustus (Marie Eugenie)'],
 ['Green', ' Miss. Mary Agatha'],
 ['Red', ' Mr. Edward H'],
 ['Red', ' Mr. Edgar Joseph']]

In [51]:
dec= {}
dec["missing"] = 0
dec["missing_name"] = []
for i in result:
    if len(i) > 1 :
        if i[0] in ["Red","Yellow","White","Pink","Green"]:
            if i[0] not in dec:
                dec[i[0]] = 1
            else :
                dec[i[0]] += 1
    elif len(i) == 1 and i not in ["Red","Yellow","White","Pink","Green"]:
        dec["missing"]+=1
        dec["missing_name"].append(i)

dec

{'missing': 2,
 'missing_name': [['Mr. Timothy J'], ['Miss. Elizabeth']],
 'Red': 13,
 'Pink': 2,
 'Yellow': 9,
 'White': 2,
 'Green': 7}

In [52]:
df = pd.DataFrame(result,columns=["colors","Name"])
df

             colors                                               Name
0               Red                                    Mr. Owen Harris
1              Pink         Mrs. John Bradley (Florence Briggs Thayer)
2            Yellow                                        Miss. Laina
3               Red                 Mrs. Jacques Heath (Lily May Peel)
4               Red                                  Mr. William Henry
5            Yellow                                          Mr. James
6     Mr. Timothy J                                               None
7            Yellow                              Master. Gosta Leonard
8             White           Mrs. Oscar W (Elisabeth Vilhelmina Berg)
9            Yellow                        Mrs. Nicholas (Adele Achem)
10            Green                               Miss. Marguerite Rut
11  Miss. Elizabeth                                               None
12           Yellow                                  Mr. William Henry
13           Yellow                                   Mr. Anders Johan
14           Yellow                        Miss. Hulda Amanda Adolfina
15           Yellow                             Mrs. (Mary D Kingcome)
16             Pink                                     Master. Eugene
17              Red                                 Mr. Charles Eugene
18            Green           Mrs. Julius (Emelia Maria Vandemoortele)
19              Red                                        Mrs. Fatima
20              Red                                       Mr. Joseph J
21            Green                                       Mr. Lawrence
22              Red                                 Miss. Anna "Annie"
23              Red                               Mr. William Thompson
24            Green                               Miss. Torborg Danira
25              Red   Mrs. Carl Oscar (Selma Augusta Emilia Johansson)
26            Green                                  Mr. Farred Chehab
27              Red                              Mr. Charles Alexander
28            White                               Miss. Ellen "Nellie"
29            Green                                          Mr. Lalio
30              Red                                      Don. Manuel E
31           Yellow              Mrs. William Augustus (Marie Eugenie)
32            Green                                  Miss. Mary Agatha
33              Red                                       Mr. Edward H
34              Red                                   Mr. Edgar Joseph

In [53]:
df["colors"].value_counts()

colors
Red                13
Yellow              9
Green               7
Pink                2
White               2
Mr. Timothy J       1
Miss. Elizabeth     1
Name: count, dtype: int64

In [54]:
df[df["Name"].isnull() == True]

             colors  Name
6     Mr. Timothy J  None
11  Miss. Elizabeth  None

In [55]:
df["Name"].isnull().sum()

2

In [56]:
Input = [
  {"region": "East", "product": "A", "sales": 100},
  {"region": "East", "product": "B", "sales": 150},
  {"region": "West", "product": "A", "sales": 200}
]

sales_df = pd.DataFrame(Input, columns=["region","product","sales"])
sales_df

  region product  sales
0   East       A    100
1   East       B    150
2   West       A    200

In [57]:
pivot = pd.pivot_table(sales_df, index="region",columns="product",values="sales",aggfunc="sum",fill_value=0)
pivot

product    A    B
region
East     100  150
West     200    0

In [58]:
freq = [
  {"product": "A", "price": 10, "sold": True},
  {"product": "B", "price": 20, "sold": False},
  {"product": "A", "price": 10, "sold": True},
  {"product": "C", "price": 15, "sold": True}
]


freq_df = pd.DataFrame(freq, columns=["product","price","sold"])
freq_df

  product  price   sold
0       A     10   True
1       B     20  False
2       A     10   True
3       C     15   True

In [59]:
result = freq_df[freq_df["sold"] == True]["product"].value_counts()
result

product
A    2
C    1
Name: count, dtype: int64

In [60]:
v1 = [10,20,30]
v2 = [10,20,30]

import numpy as np 

def find_similiarity(v1,v2):
    a = np.sqrt(sum( i*i  for i in v1))
    b = np.sqrt(sum( i*i  for i in v2))
    dot = sum(i*j  for i,j in zip(v1,v2))
    return dot/(a*b)

In [61]:
print(find_similiarity(v1,v2))

0.9999999999999999

In [62]:
v1 = [1, 0, 0]
v2 = [0, 1, 0]
print(find_similiarity(v1,v2))

0.0

In [63]:
def find_mex(arr):
    sort = sorted(arr)
    if len(sort) == 0:
        return 0
    for i in range(len(sort)):
        if i != sort[i]:
            return i
    return max(sort) +1

In [64]:
print(find_mex([]))              # Output: 0
print(find_mex([1,2,3,4,5,10]))  # Output: 0
print(find_mex([0,1,2,3,4,5,6])) # Output: 7
print(find_mex([0,1,3,4,1000]))  # Output: 2
print(find_mex([0,2,3,4,5,6]))

0
0
7
2
1

In [65]:
st = "***Hello there***"
print(st.strip("*"))

Hello there

In [66]:
def parese_passanger_data(data):
    result=[]
    ldata= data.splitlines()
    for row in ldata:
        dec ={}
        temp = row.split(",")
        if len(temp) > 1:
            tec = temp[1].split(".")
            if temp[0] in ["Red","Yellow","Pink"]:
                 dec["color"] = temp[0]
            dec["title"] = tec[0]
            dec["name"] = tec[1].strip()
        else :
            temp = row.split(".")
            dec["title"] = temp[0]
            dec["name"] = temp[1].strip()
        result.append(dec)
                    
    return result

result = parese_passanger_data("""Red, Mr. Owen Harris
Pink, Mrs. John Bradley (Florence Briggs Thayer)
Yellow, Miss. Laina
Red, Mrs. Jacques Heath (Lily May Peel)
Red, Mr. William Henry
Yellow, Mr. James
Mr. Timothy J
Yellow, Master. Gosta Leonard""")

In [67]:
import pandas as pd

In [68]:
df = pd.DataFrame(result, columns=["color","title","name"])
df

    color    title                                   name
0     Red       Mr                            Owen Harris
1    Pink      Mrs  John Bradley (Florence Briggs Thayer)
2  Yellow     Miss                                  Laina
3     Red      Mrs          Jacques Heath (Lily May Peel)
4     Red       Mr                          William Henry
5  Yellow       Mr                                  James
6     NaN       Mr                              Timothy J
7  Yellow   Master                          Gosta Leonard

In [69]:
df[df["color"]!= None]

    color    title                                   name
0     Red       Mr                            Owen Harris
1    Pink      Mrs  John Bradley (Florence Briggs Thayer)
2  Yellow     Miss                                  Laina
3     Red      Mrs          Jacques Heath (Lily May Peel)
4     Red       Mr                          William Henry
5  Yellow       Mr                                  James
6     NaN       Mr                              Timothy J
7  Yellow   Master                          Gosta Leonard

In [70]:
df[df["color"].isnull() == True]

  color title       name
6   NaN    Mr  Timothy J

In [71]:
import numpy as np

# Dataset
X = np.array([1, 2, 3, 4, 5])
y = np.array([2, 4, 6, 8, 10])

# Initialize parameters
m = 0.0
b = 0.0
learning_rate = 0.01
epochs = 1000
n = len(X)

# Gradient Descent
for epoch in range(epochs):
    # Predictions
    y_pred = m * X + b
    
    # Calculate loss (MSE)
    loss = (1/n) * np.sum((y - y_pred)**2)
    
    # Calculate gradients
    dm = -(2/n) * np.sum(X * (y - y_pred))
    db = -(2/n) * np.sum(y - y_pred)
    
    # Update parameters
    m = m - learning_rate * dm
    b = b - learning_rate * db
    
    # Print every 100 epochs
    if epoch % 100 == 0:
        print(f"Epoch {epoch}: Loss={loss:.4f}, m={m:.4f}, b={b:.4f}")

print(f"\nFinal: m={m:.4f}, b={b:.4f}")

Epoch 0: Loss=44.0000, m=0.4400, b=0.1200
Epoch 100: Loss=0.0245, m=1.8988, b=0.3655
Epoch 200: Loss=0.0124, m=1.9279, b=0.2605
Epoch 300: Loss=0.0063, m=1.9486, b=0.1856
Epoch 400: Loss=0.0032, m=1.9634, b=0.1323
Epoch 500: Loss=0.0016, m=1.9739, b=0.0943
Epoch 600: Loss=0.0008, m=1.9814, b=0.0672
Epoch 700: Loss=0.0004, m=1.9867, b=0.0479
Epoch 800: Loss=0.0002, m=1.9905, b=0.0341
Epoch 900: Loss=0.0001, m=1.9933, b=0.0243

Final: m=1.9952, b=0.0174