In [1]:
import pandas as pd 
import numpy as np 
import plotly.graph_objects as go 
import plotly.express as px

In [2]:
df  = pd.read_csv(r"C:\works\learnings\analysis\customer_shopping_data.csv")
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon

In [3]:
df.describe()

                age      quantity         price
count  99457.000000  99457.000000  99457.000000
mean      43.427089      3.003429    689.256321
std       14.990054      1.413025    941.184567
min       18.000000      1.000000      5.230000
25%       30.000000      2.000000     45.450000
50%       43.000000      3.000000    203.300000
75%       56.000000      4.000000   1200.320000
max       69.000000      5.000000   5250.000000

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   invoice_no      99457 non-null  object
 1   customer_id     99457 non-null  object
 2   gender          99457 non-null  object
 3   age             99457 non-null  int64
 4   category        99457 non-null  object
 5   quantity        99457 non-null  int64
 6   price           99457 non-null  float64
 7   payment_method  99457 non-null  object
 8   invoice_date    99457 non-null  object
 9   shopping_mall   99457 non-null  object
dtypes: float64(1), int64(2), object(7)
memory usage: 7.6+ MB

In [5]:
df.isna().sum()

invoice_no        0
customer_id       0
gender            0
age               0
category          0
quantity          0
price             0
payment_method    0
invoice_date      0
shopping_mall     0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(0)

In [7]:
df["total_revenue"] = df["quantity"] * df["price"]
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,5/8/2022,Kanyon,7502.00
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,12/12/2021,Forum Istanbul,5401.53
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,9/11/2021,Metrocity,300.08
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,16/05/2021,Metropol AVM,15004.25
4,I337046,C189076,Female,53,Books,4,60.60,Cash,24/10/2021,Kanyon,242.40

In [8]:
df["invoice_date"] =  pd.to_datetime(df["invoice_date"], format = "%d/%m/%Y") 
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,300.08
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,15004.25
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,242.40

In [9]:
df["month"] = df["invoice_date"].dt.month_name()
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue,month
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00,August
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53,December
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,300.08,November
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,15004.25,May
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,242.40,October

In [10]:
customer_life_time = (df.groupby("customer_id")["invoice_date"].max() - df.groupby("customer_id")["invoice_date"].min()).dt.days.reset_index(name="customer_life_time")

In [11]:
# customer_life_time.value_counts()

In [12]:
# min(df["invoice_date"]),max(df["invoice_date"])

In [13]:
df[df["customer_id"] == df["customer_id"].iloc[1000]].sort_values("invoice_date")

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue,month
1000,I225840,C325548,Female,23,Food & Beverage,3,15.69,Credit Card,2021-07-20,Cevahir AVM,47.07,July

In [14]:
df = df.merge(customer_life_time, on="customer_id", how="left")
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue,month,customer_life_time
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00,August,0
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53,December,0
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,300.08,November,0
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,15004.25,May,0
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,242.40,October,0

In [15]:
df["category"].value_counts()

category
Clothing           34487
Cosmetics          15097
Food & Beverage    14776
Toys               10087
Shoes              10034
Souvenir            4999
Technology          4996
Books               4981
Name: count, dtype: int64

In [16]:
category_avg_price = df.groupby("category")["total_revenue"].mean().reset_index()
category_avg_price.sort_values(by="total_revenue",ascending=True)

          category  total_revenue
3  Food & Beverage      57.494251
5         Souvenir     127.190368
0            Books     167.547260
7             Toys     394.609521
2        Cosmetics     449.947864
1         Clothing    3305.500364
4            Shoes    6632.793649
6       Technology   11581.735388

In [17]:
df["customer_id"].nunique()

99457

In [18]:
df = df.merge(category_avg_price, on="category", how='left')
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue_x,month,customer_life_time,total_revenue_y
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00,August,0,3305.500364
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53,December,0,6632.793649
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,300.08,November,0,3305.500364
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,15004.25,May,0,6632.793649
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,242.40,October,0,167.547260

In [19]:
df =df.rename(columns={"total_revenue_x" : "total_revenue" , "total_revenue_y" : "Avg_category_price"})

In [20]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue,month,customer_life_time,Avg_category_price
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00,August,0,3305.500364
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53,December,0,6632.793649
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,300.08,November,0,3305.500364
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,15004.25,May,0,6632.793649
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,242.40,October,0,167.547260

In [21]:
df["day_name"] = df["invoice_date"].dt.day_name()
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue,month,customer_life_time,Avg_category_price,day_name
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00,August,0,3305.500364,Friday
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53,December,0,6632.793649,Sunday
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,300.08,November,0,3305.500364,Tuesday
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,15004.25,May,0,6632.793649,Sunday
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,242.40,October,0,167.547260,Sunday

In [22]:
df.columns

Index(['invoice_no', 'customer_id', 'gender', 'age', 'category', 'quantity',
       'price', 'payment_method', 'invoice_date', 'shopping_mall',
       'total_revenue', 'month', 'customer_life_time', 'Avg_category_price',
       'day_name'],
      dtype='object')

In [23]:
print(df.head())

  invoice_no customer_id  gender  age  category  quantity    price  \
0    I138884     C241288  Female   28  Clothing         5  1500.40
1    I317333     C111565    Male   21     Shoes         3  1800.51
2    I127801     C266599    Male   20  Clothing         1   300.08
3    I173702     C988172  Female   66     Shoes         5  3000.85
4    I337046     C189076  Female   53     Books         4    60.60

  payment_method invoice_date   shopping_mall  total_revenue     month  \
0    Credit Card   2022-08-05          Kanyon        7502.00    August
1     Debit Card   2021-12-12  Forum Istanbul        5401.53  December
2           Cash   2021-11-09       Metrocity         300.08  November
3    Credit Card   2021-05-16    Metropol AVM       15004.25       May
4           Cash   2021-10-24          Kanyon         242.40   October

   customer_life_time  Avg_category_price day_name
0                   0         3305.500364   Friday
1                   0         6632.793649   Sunday
2                   0         3305.500364  Tuesday
3                   0         6632.793649   Sunday
4                   0          167.547260   Sunday

In [24]:
def age_calculation(age):
    if age <= 19 :
        return "Under 20's"
    elif 20 <= age <= 29 :
        return "20's"
    elif 30 <= age <= 39 :
        return "30's"
    elif 40 <= age <= 49 :
        return "40's"
    elif 50 <= age <= 59 :
        return "50's"
    else :
        return "60's"

In [25]:
age_calculation(55)

"50's"

In [26]:
df["age_group"] = [ age_calculation(age) for age in df["age"]]

In [27]:
df.head()

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue,month,customer_life_time,Avg_category_price,day_name,age_group
0,I138884,C241288,Female,28,Clothing,5,1500.40,Credit Card,2022-08-05,Kanyon,7502.00,August,0,3305.500364,Friday,20's
1,I317333,C111565,Male,21,Shoes,3,1800.51,Debit Card,2021-12-12,Forum Istanbul,5401.53,December,0,6632.793649,Sunday,20's
2,I127801,C266599,Male,20,Clothing,1,300.08,Cash,2021-11-09,Metrocity,300.08,November,0,3305.500364,Tuesday,20's
3,I173702,C988172,Female,66,Shoes,5,3000.85,Credit Card,2021-05-16,Metropol AVM,15004.25,May,0,6632.793649,Sunday,60's
4,I337046,C189076,Female,53,Books,4,60.60,Cash,2021-10-24,Kanyon,242.40,October,0,167.547260,Sunday,50's

In [28]:
df["age_group"].value_counts()

age_group
30's          19287
20's          19263
40's          19153
60's          19043
50's          18931
Under 20's     3780
Name: count, dtype: int64

In [29]:
age_group_spending = df.groupby("age_group")["total_revenue"].sum().reset_index()
age_group_spending

    age_group  total_revenue
0        20's    49044390.58
1        30's    48288158.82
2        40's    49234368.09
3        50's    47593634.14
4        60's    48294183.73
5  Under 20's     9051058.89

In [30]:
age_analysis = df.groupby('age_group').agg({
    'total_revenue': ['sum', 'mean', 'count'],
    "customer_id" : "count",
    'quantity': 'mean'
}).round(2)

age_analysis

           total_revenue                 customer_id quantity
                     sum     mean  count       count     mean
age_group
20's         49044390.58  2546.04  19263       19263     3.01
30's         48288158.82  2503.66  19287       19287     3.00
40's         49234368.09  2570.58  19153       19153     3.00
50's         47593634.14  2514.06  18931       18931     3.01
60's         48294183.73  2536.06  19043       19043     3.00
Under 20's    9051058.89  2394.46   3780        3780     2.99

In [31]:
fig = go.Figure(
    data=[
        go.Bar(
            x = age_group_spending["age_group"],
            y = age_group_spending["total_revenue"],
            text= age_group_spending["total_revenue"],
            textposition="outside"
        )
    ]
)

fig.update_layout(
    title="Spending by Age Group",
    xaxis_title="Age Group",
    yaxis_title="Total Spending",
    template="plotly_dark",
    height = 500
)

fig.show()

In [32]:
total_revenue_gender = df.groupby("gender")["total_revenue"].sum().reset_index()
total_revenue_gender

   gender  total_revenue
0  Female   1.502071e+08
1    Male   1.012987e+08

In [33]:
fig = go.Figure(
    data=[
        go.Bar(
            x = total_revenue_gender["gender"],
            y = total_revenue_gender["total_revenue"],
            text= total_revenue_gender["total_revenue"],
            textposition="outside"
        )
    ]
)

fig.update_layout(
    title="Spending by Gender",
    xaxis_title="Gender",
    yaxis_title="Total Spending",
    template="plotly_dark",
    height = 500
)

fig.show()

In [34]:
df["shopping_mall"].nunique()

10

In [35]:
df["payment_method"].value_counts()

payment_method
Cash           44447
Credit Card    34931
Debit Card     20079
Name: count, dtype: int64

In [36]:
payment_method = df.groupby(["gender","payment_method"]).agg({
    "total_revenue" : ["mean", "sum", "count"],
    "quantity" : "mean" 
}).reset_index()

payment_method

   gender payment_method total_revenue                      quantity
                                  mean          sum  count      mean
0  Female           Cash   2549.082894  67573638.45  26509  2.998906
1  Female    Credit Card   2516.577502  52875809.90  21011  3.012279
2  Female     Debit Card   2487.684975  29757687.67  11962  2.998662
3    Male           Cash   2523.057452  45258604.57  17938  3.003233
4    Male    Credit Card   2528.830019  35201313.87  13920  2.999569
5    Male     Debit Card   2567.295773  20838739.79   8117  3.009363

In [37]:
payment_method.columns = ['gender', 'payment_method', 'avg_revenue', 'total_revenue', 'count_orders', 'avg_quantity']

fig = go.Figure()

for gender in payment_method["gender"].unique():
    gender_df = payment_method[payment_method["gender"] == gender]
    fig.add_trace(
        go.Bar(
            x=gender_df["payment_method"],
            y=gender_df["total_revenue"],
            name=gender,  # legend label
            text=gender_df["total_revenue"].round(2),
            textposition="outside"
        )
    )

# --- Layout ---
fig.update_layout(
    barmode="group",  # side-by-side bars
    title="Total Revenue by Payment Method and Gender",
    xaxis_title="Payment Method",
    yaxis_title="Total Revenue",
    template="plotly_dark",
    height=500
)

fig.show()

In [38]:
revenue_based_on_mall = df.groupby(["shopping_mall","payment_method"]).agg({
    "total_revenue" : [ "mean", "sum"],
    "quantity" : "sum"
}).reset_index()

revenue_based_on_mall

        shopping_mall payment_method total_revenue              quantity
                                              mean          sum      sum
0         Cevahir AVM           Cash   2526.002370   5627933.28     6765
1         Cevahir AVM    Credit Card   2457.320112   4371572.48     5226
2         Cevahir AVM     Debit Card   2688.650854   2645632.44     2958
3   Emaar Square Mall           Cash   2711.105000   5731275.97     6446
4   Emaar Square Mall    Credit Card   2504.665531   4247912.74     5092
5   Emaar Square Mall     Debit Card   2424.487093   2426911.58     2963
6      Forum Istanbul           Cash   2403.804737   5247505.74     6481
7      Forum Istanbul    Credit Card   2487.189800   4352582.15     5296
8      Forum Istanbul     Debit Card   2666.502318   2703833.35     3075
9        Istinye Park           Cash   2483.588481  11017198.50    13219
10       Istinye Park    Credit Card   2564.346666   8775194.29    10396
11       Istinye Park     Debit Card   2509.846537   4826434.89     5850
12             Kanyon           Cash   2593.655740  22961634.27    26477
13             Kanyon    Credit Card   2447.994252  16930328.25    20739
14             Kanyon     Debit Card   2630.061317  10662268.58    12241
15   Mall of Istanbul           Cash   2577.246841  22922033.40    26895
16   Mall of Istanbul    Credit Card   2530.503409  17761603.43    21103
17   Mall of Istanbul     Debit Card   2528.249342  10188844.85    12116
18          Metrocity           Cash   2511.470975  16638495.21    19655
19          Metrocity    Credit Card   2510.806037  13425279.88    16068
20          Metrocity     Debit Card   2382.037591   7239012.24     9171
21       Metropol AVM           Cash   2496.268671  11380488.87    13787
22       Metropol AVM    Credit Card   2556.240307   9000522.12    10630
23       Metropol AVM     Debit Card   2402.163479   4998902.20     6113
24     Viaport Outlet           Cash   2547.720027   5683963.38     6670
25     Viaport Outlet    Credit Card   2595.735212   4467260.30     5194
26     Viaport Outlet     Debit Card   2463.738087   2370116.04     2852
27       Zorlu Center           Cash   2418.982100   5621714.40     6975
28       Zorlu Center    Credit Card   2695.947801   4744868.13     5301
29       Zorlu Center     Debit Card   2557.488688   2534471.29     2958

In [39]:
revenue_based_on_mall.columns = [
    "shopping_mall",
    "payment_method",
    "avg_revenue",
    "total_revenue",
    "total_quantity"
]

In [40]:
fig = px.bar(
    revenue_based_on_mall,
    x="shopping_mall",
    y="total_revenue",
    color="payment_method",
    barmode="group",
    title="Total Revenue by Shopping Mall and Payment Method",
    template="plotly_dark"
)

fig.update_layout(
    xaxis_title="Shopping Mall",
    yaxis_title="Total Revenue",
    height=500
)

fig.show()

In [41]:
gender_category_revenue = df.groupby(["gender", "category"]).agg({
    "total_revenue" : ["mean", "sum", "count"]
}).round(2).reset_index()
print(gender_category_revenue)

    gender         category total_revenue
                                     mean          sum  count
0   Female            Books        168.38    489314.70   2906
1   Female         Clothing       3304.85  68251695.60  20652
2   Female        Cosmetics        448.38   4066772.54   9070
3   Female  Food & Beverage         57.40    505322.60   8804
4   Female            Shoes       6607.20  39425167.30   5967
5   Female         Souvenir        126.90    382867.20   3017
6   Female       Technology      11630.31  34669950.00   2981
7   Female             Toys        397.05   2416046.08   6085
8     Male            Books        166.38    345238.20   2075
9     Male         Clothing       3306.48  45745095.44  13835
10    Male        Cosmetics        452.31   2726090.36   6027
11    Male  Food & Beverage         57.64    344212.45   5972
12    Male            Shoes       6670.34  27128284.17   4067
13    Male         Souvenir        127.63    252957.45   1982
14    Male       Technology      11509.88  23192400.00   2015
15    Male             Toys        390.90   1564380.16   4002

In [42]:
month_order = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']

In [43]:
monthly_revenue = df.groupby("month")["total_revenue"].sum().reset_index()
monthly_revenue["month"] = pd.Categorical(
    monthly_revenue["month"],
    categories=month_order,
    ordered= True
)
monthly_revenue = monthly_revenue.sort_values(by="month", ascending= True)
print(monthly_revenue)

        month  total_revenue
4     January    28891525.59
3    February    26625090.10
7       March    21956191.33
0       April    18715685.98
8         May    19719331.10
6        June    18933775.30
5        July    20378722.63
1      August    19282361.29
11  September    18795794.91
10    October    20545090.43
9    November    18207139.95
2    December    19455085.64

In [44]:
fig = go.Figure(
    data=[
        go.Scatter(
            x = monthly_revenue["month"],
            y = monthly_revenue["total_revenue"],
            mode = "lines+markers",
            line = dict(color = "orange", width = 3),
            marker = dict(size=10, color="white", line=dict(width=2, color="orange"))
        )
    ]
)

fig.update_layout(
    xaxis_title = "Months",
    yaxis_title = "Total Revenue each month",
    height = 500,
    title = "Revenue based on each month",
    template = "plotly_dark"
)

fig.show()

In [45]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

In [46]:
best_performing_cat = df.groupby(["month", "category"]).agg({
    "total_revenue" : ["mean", "sum", "count"]
}).reset_index()
best_performing_cat

        month         category total_revenue
                                        mean          sum count
0       April            Books    164.257895     62418.00   380
1       April         Clothing   3346.277882   8847558.72  2644
2       April        Cosmetics    444.820400    489302.44  1100
3       April  Food & Beverage     57.181631     66959.69  1171
4       April            Shoes   6625.390176   4902788.73   740
5       April         Souvenir    123.061063     48609.12   395
6       April       Technology  11504.871060   4015200.00   349
7       April             Toys    399.504633    282849.28   708
8      August            Books    175.106746     66190.35   378
9      August         Clothing   3275.519465   8332921.52  2544
10     August        Cosmetics    456.560629    536915.30  1176
11     August  Food & Beverage     55.994461     63889.68  1141
12     August            Shoes   6713.319385   5350515.55   797
13     August         Souvenir    133.552410     55424.25   415
14     August       Technology  11210.294118   4573800.00   408
15     August             Toys    390.083299    302704.64   776
16   December            Books    173.493211     66447.90   383
17   December         Clothing   3296.147232   8777640.08  2663
18   December        Cosmetics    454.976239    525042.58  1154
19   December  Food & Beverage     59.209480     69511.93  1174
20   December            Shoes   6419.143083   5039027.32   785
21   December         Souvenir    135.646923     47612.07   351
22   December       Technology  12274.137931   4627350.00   377
23   December             Toys    381.404489    302453.76   793
24   February            Books    164.982110     89915.25   545
25   February         Clothing   3268.944431  12010101.84  3674
26   February        Cosmetics    452.607930    701994.90  1551
27   February  Food & Beverage     55.359121     84422.66  1525
28   February            Shoes   6885.250467   6926561.97  1006
29   February         Souvenir    129.489181     72772.92   562
30   February       Technology  11711.388889   6324150.00   540
31   February             Toys    384.773457    415170.56  1079
32    January            Books    170.541267     99596.10   584
33    January         Clothing   3287.667976  12992863.84  3952
34    January        Cosmetics    447.304903    810069.18  1811
35    January  Food & Beverage     56.592400     95018.64  1679
36    January            Shoes   6292.007794   7531533.33  1197
37    January         Souvenir    125.406401     78755.22   628
38    January       Technology  11819.791667   6808200.00   576
39    January             Toys    402.615817    475489.28  1181
40       July            Books    173.404064     70402.05   406
41       July         Clothing   3326.360477   9480127.36  2850
42       July        Cosmetics    445.076673    505607.10  1136
43       July  Food & Beverage     58.347478     65699.26  1126
44       July            Shoes   6932.196124   5365519.80   774
45       July         Souvenir    128.707747     46849.62   364
46       July       Technology  11046.715328   4540200.00   411
47       July             Toys    375.700543    304317.44   810
48       June            Books    166.818333     60054.60   360
49       June         Clothing   3276.386043   8469457.92  2585
50       June        Cosmetics    437.434967    523172.22  1196
51       June  Food & Beverage     58.939119     68251.50  1158
52       June            Shoes   6639.725664   5052831.23   761
53       June         Souvenir    124.162655     48175.11   388
54       June       Technology  11691.666667   4419450.00   378
55       June             Toys    387.261881    292382.72   755
56      March            Books    160.496358     72704.85   453
57      March         Clothing   3308.699674  10157708.00  3070
58      March        Cosmetics    447.321097    595384.38  1331
59      March  Food & Beverage     59.115344     75667.64  1280
60      March            Shoes   6578.359532   6045512.41   919
61      March         Souvenir    126.256950     53406.69   423
62      March       Technology  11220.437956   4611600.00   411
63      March             Toys    408.312408    344207.36   843
64        May            Books    165.862987     63857.25   385
65        May         Clothing   3375.985737   8861962.56  2625
66        May        Cosmetics    453.806649    521423.84  1149
67        May  Food & Beverage     58.061102     67467.00  1162
68        May            Shoes   6631.732828   5464547.85   824
69        May         Souvenir    126.773008     46779.24   369
70        May       Technology  11772.983871   4379550.00   372
71        May             Toys    386.859877    313743.36   811
72   November            Books    159.748333     57509.40   360
73   November         Clothing   3285.241390   8699319.20  2648
74   November        Cosmetics    455.006431    527807.46  1160
75   November  Food & Beverage     57.295409     65144.88  1137
76   November            Shoes   6651.954908   4702932.12   707
77   November         Souvenir    118.585909     44351.13   374
78   November       Technology  10526.323120   3778950.00   359
79   November             Toys    404.799218    331125.76   818
80    October            Books    166.883676     64917.75   389
81    October         Clothing   3351.491847   8961889.20  2674
82    October        Cosmetics    450.999632    539395.56  1196
83    October  Food & Beverage     56.836814     66896.93  1177
84    October            Shoes   6829.547394   5292899.23   775
85    October         Souvenir    126.761768     45887.76   362
86    October       Technology  12120.967742   5260500.00   434
87    October             Toys    413.083223    312704.00   757
88  September            Books    169.104469     60539.40   358
89  September         Clothing   3285.864269   8405240.80  2558
90  September        Cosmetics    454.483676    516747.94  1137
91  September  Food & Beverage     57.940000     60605.24  1046
92  September            Shoes   6513.727543   4878781.93   749
93  September         Souvenir    128.265000     47201.52   368
94  September       Technology  11872.440945   4523400.00   381
95  September             Toys    401.161481    303278.08   756

In [47]:
best_performing_cat.columns = ['month', 'category', 'avg_revenue', 'total_revenue', 'count']
max_revenue = best_performing_cat.loc[best_performing_cat.groupby("month")["total_revenue"].idxmax()].reset_index()
max_revenue

    index      month  category  avg_revenue  total_revenue  count
0       1      April  Clothing  3346.277882     8847558.72   2644
1       9     August  Clothing  3275.519465     8332921.52   2544
2      17   December  Clothing  3296.147232     8777640.08   2663
3      25   February  Clothing  3268.944431    12010101.84   3674
4      33    January  Clothing  3287.667976    12992863.84   3952
5      41       July  Clothing  3326.360477     9480127.36   2850
6      49       June  Clothing  3276.386043     8469457.92   2585
7      57      March  Clothing  3308.699674    10157708.00   3070
8      65        May  Clothing  3375.985737     8861962.56   2625
9      73   November  Clothing  3285.241390     8699319.20   2648
10     81    October  Clothing  3351.491847     8961889.20   2674
11     89  September  Clothing  3285.864269     8405240.80   2558

In [48]:
print(max_revenue)

    index      month  category  avg_revenue  total_revenue  count
0       1      April  Clothing  3346.277882     8847558.72   2644
1       9     August  Clothing  3275.519465     8332921.52   2544
2      17   December  Clothing  3296.147232     8777640.08   2663
3      25   February  Clothing  3268.944431    12010101.84   3674
4      33    January  Clothing  3287.667976    12992863.84   3952
5      41       July  Clothing  3326.360477     9480127.36   2850
6      49       June  Clothing  3276.386043     8469457.92   2585
7      57      March  Clothing  3308.699674    10157708.00   3070
8      65        May  Clothing  3375.985737     8861962.56   2625
9      73   November  Clothing  3285.241390     8699319.20   2648
10     81    October  Clothing  3351.491847     8961889.20   2674
11     89  September  Clothing  3285.864269     8405240.80   2558

In [49]:
max = df.groupby("category")["total_revenue"].sum().sort_values(ascending=False)
max

category
Clothing           1.139968e+08
Shoes              6.655345e+07
Technology         5.786235e+07
Cosmetics          6.792863e+06
Toys               3.980426e+06
Food & Beverage    8.495351e+05
Books              8.345529e+05
Souvenir           6.358247e+05
Name: total_revenue, dtype: float64

In [50]:
max_mall_revenue = df.groupby("shopping_mall")["total_revenue"].sum().reset_index()
max_mall_revenue.sort_values(by="total_revenue",ascending = False)

       shopping_mall  total_revenue
5   Mall of Istanbul    50872481.68
4             Kanyon    50554231.10
6          Metrocity    37302787.33
7       Metropol AVM    25379913.19
3       Istinye Park    24618827.68
9       Zorlu Center    12901053.82
0        Cevahir AVM    12645138.20
8     Viaport Outlet    12521339.72
1  Emaar Square Mall    12406100.29
2     Forum Istanbul    12303921.24

In [51]:
day_order = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']

In [52]:
day_based_revenue = df.groupby("day_name")["total_revenue"].sum().reset_index()
day_based_revenue["day_name"] = pd.Categorical(
    day_based_revenue["day_name"],
    categories= day_order,
    ordered= True
)
day_based_revenue = day_based_revenue.sort_values(by="day_name", ascending = True)

In [53]:
day_based_revenue.columns= ["day_name", "total_revenue"]

fig_2 = go.Figure(
    data = [
            go.Scatter(
            x= day_based_revenue["day_name"],
            y= day_based_revenue["total_revenue"],
            mode = "lines+markers",
            line = dict(color = "white", width = 3),
            marker = dict(color = "red", size = 10, line= dict(color = "white", width = 2))
        )
    ]
)

fig_2.update_layout(
    xaxis_title = "Day Name",
    yaxis_title = "Total Revenue",
    height = 500,
    width = 600,
    title = "Revenue based on Day",
    template = "plotly_dark"
)

fig_2.show()

In [54]:
# Example for mall analysis
max_mall_revenue.sort_values(by="total_revenue", ascending=False)

# ADD THIS:
print("\n📊 KEY INSIGHTS:")
print(f"Top performing mall: {max_mall_revenue.iloc[0]['shopping_mall']}")
print(f"Revenue: ${max_mall_revenue.iloc[0]['total_revenue']:,.2f}")
print(f"Bottom mall: {max_mall_revenue.iloc[-1]['shopping_mall']}")
print(f"Revenue difference: ${(max_mall_revenue.iloc[0]['total_revenue'] - max_mall_revenue.iloc[-1]['total_revenue']):,.2f}")

📊 KEY INSIGHTS:
Top performing mall: Cevahir AVM
Revenue: $12,645,138.20
Bottom mall: Zorlu Center
Revenue difference: $-255,915.62

In [55]:

# Example for mall analysis
day_based_revenue = day_based_revenue.sort_values(by="total_revenue", ascending=False)

# ADD THIS:
print("\n📊 KEY INSIGHTS:")
print(f"Top performing days: {day_based_revenue.iloc[0]['day_name']}")
print(f"Revenue: ${day_based_revenue.iloc[0]['total_revenue']:,.2f}")
print(f"Bottom day: {day_based_revenue.iloc[-1]['day_name']}")
print(f"Revenue difference: ${(day_based_revenue.iloc[0]['total_revenue'] - day_based_revenue.iloc[-1]['total_revenue']):,.2f}")

📊 KEY INSIGHTS:
Top performing days: Monday
Revenue: $37,296,648.11
Bottom day: Saturday
Revenue difference: $2,116,819.39

In [56]:
# Monday vs Saturday comparison by category
monday_sat_compare = df[df['day_name'].isin(['Monday', 'Saturday'])].groupby(['day_name', 'category'])['total_revenue'].sum().reset_index()

# Pivot for easy comparison
comparison = monday_sat_compare.pivot(index='category', columns='day_name', values='total_revenue')
comparison['Difference'] = comparison['Monday'] - comparison['Saturday']
comparison.sort_values('Difference', ascending=False)

day_name              Monday     Saturday  Difference
category
Clothing         16803879.84  15613162.40  1190717.44
Technology        8888250.00   8435700.00   452550.00
Shoes             9671739.55   9255821.74   415917.81
Toys               617487.36    587704.32    29783.04
Cosmetics          979621.38    955103.40    24517.98
Souvenir            93288.69     89582.01     3706.68
Food & Beverage    120802.54    117570.40     3232.14
Books              121578.75    125184.45    -3605.70

In [57]:
# Create year-month column
df['year_month'] = df['invoice_date'].dt.to_period('M')

# Group by month
monthly_revenue = df.groupby('year_month')['total_revenue'].sum().reset_index()
monthly_revenue['year_month'] = monthly_revenue['year_month'].dt.to_timestamp()

# Create time series chart
fig_1 = px.line(monthly_revenue, 
              x='year_month', 
              y='total_revenue',
              title='Revenue Trend: January 2021 - March 2023',
              template='plotly_dark')
fig_1.update_traces(line_color='cyan', line_width=3, mode='lines+markers')
fig_1.update_xaxes(title_text='Month')
fig_1.update_yaxes(title_text='Total Revenue ($)')
fig_1.show()

In [58]:
summary_df = df.groupby("category")["total_revenue"].sum().reset_index()
summary_df.to_csv("cleaned_summary.csv", index=False)

In [59]:
df["gender"].value_counts()

gender
Female    59482
Male      39975
Name: count, dtype: int64

In [62]:
from scipy import stats 

female_revenue = df[df["gender"] == "Female"]["total_revenue"]
male_revenue = df[df["gender"] == "Male"]["total_revenue"]

t_stat, p_value = stats.ttest_ind(female_revenue,male_revenue)
print(f"Gender revenue difference is { 'significant'  if p_value < 0.05 else 'Not significant'} (p = {p_value:.4f})")

Gender revenue difference is Not significant (p = 0.7474)

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99457 entries, 0 to 99456
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   invoice_no          99457 non-null  object
 1   customer_id         99457 non-null  object
 2   gender              99457 non-null  object
 3   age                 99457 non-null  int64
 4   category            99457 non-null  object
 5   quantity            99457 non-null  int64
 6   price               99457 non-null  float64
 7   payment_method      99457 non-null  object
 8   invoice_date        99457 non-null  datetime64[ns]
 9   shopping_mall       99457 non-null  object
 10  total_revenue       99457 non-null  float64
 11  month               99457 non-null  object
 12  customer_life_time  99457 non-null  int64
 13  Avg_category_price  99457 non-null  float64
 14  day_name            99457 non-null  object
 15  age_group           99457 non-null  object
 16  year_month          99457 non-null  period[M]
dtypes: datetime64[ns](1), float64(3), int64(3), object(9), period[M](1)
memory usage: 12.9+ MB

In [65]:
numeric_cols = df.select_dtypes(include=["int64", "float64"])
corr_matrix = numeric_cols.corr()
corr_matrix

,age,quantity,price,total_revenue,customer_life_time,Avg_category_price
age,1.000000,0.000667,0.001694,0.002731,NaN,-0.000667
quantity,0.000667,1.000000,0.344880,0.461173,NaN,0.001679
price,0.001694,0.344880,1.000000,0.962372,NaN,0.850213
total_revenue,0.002731,0.461173,0.962372,1.000000,NaN,0.695314
customer_life_time,NaN,NaN,NaN,NaN,NaN,NaN
Avg_category_price,-0.000667,0.001679,0.850213,0.695314,NaN,1.000000

In [69]:
df["invoice_date"].nunique()

797

In [70]:
# Average basket size by category
basket_analysis = df.groupby('invoice_no').agg({
    'category': 'count',
    'total_revenue': 'sum',
    'quantity': 'sum'
}).describe()

basket_analysis

       category  total_revenue      quantity
count   99457.0   99457.000000  99457.000000
mean        1.0    2528.789268      3.003429
std         0.0    4222.475781      1.413025
min         1.0       5.230000      1.000000
25%         1.0     136.350000      2.000000
50%         1.0     600.170000      3.000000
75%         1.0    2700.720000      4.000000
max         1.0   26250.000000      5.000000

In [78]:
df[df["customer_id"] == "C241288"]

,invoice_no,customer_id,gender,age,category,quantity,price,payment_method,invoice_date,shopping_mall,total_revenue,year_month,day_name
0,I138884,C241288,Female,28,Clothing,5,1500.4,Credit Card,2022-08-05,Kanyon,7502.0,2022-08-01,Friday

In [76]:
import dash
from dash import html, dcc, Input, Output
import plotly.express as px
import plotly.graph_objects as go
import pandas as pd

# Initialize app
app = dash.Dash(__name__)

# Load the FULL dataset (not the summary)
df = pd.read_csv(r"C:\works\learnings\analysis\customer_shopping_data.csv")

# Data preparation
df['invoice_date'] = pd.to_datetime(df['invoice_date'], format="%d/%m/%Y")
df['total_revenue'] = df['quantity'] * df['price']
df['year_month'] = df['invoice_date'].dt.to_period('M').dt.to_timestamp()
df['day_name'] = df['invoice_date'].dt.day_name()

# Calculate KPIs
total_revenue = df['total_revenue'].sum()
total_customers = df['customer_id'].nunique()
avg_order_value = df.groupby('invoice_no')['total_revenue'].sum().mean()
total_orders = df['invoice_no'].nunique()

# Prepare data for charts
category_revenue = df.groupby('category')['total_revenue'].sum().reset_index()
monthly_revenue = df.groupby('year_month')['total_revenue'].sum().reset_index()
mall_revenue = df.groupby('shopping_mall')['total_revenue'].sum().reset_index()

# App layout
app.layout = html.Div([
    html.Div([
        html.H1("🛍️ Customer Shopping Dashboard", 
                style={'textAlign': 'center', 'color': '#00d4ff', 'marginBottom': '30px'}),
    ]),
    
    # Filters Section
    html.Div([
        html.Div([
            html.Label("Select Mall:", style={'color': 'white', 'fontWeight': 'bold'}),
            dcc.Dropdown(
                id='mall-filter',
                options=[{'label': 'All Malls', 'value': 'All'}] + 
                        [{'label': mall, 'value': mall} for mall in sorted(df['shopping_mall'].unique())],
                value='All',
                style={'width': '300px', 'color': 'black'}
            )
        ], style={'display': 'inline-block', 'marginRight': '20px'}),
        
        html.Div([
            html.Label("Select Category:", style={'color': 'white', 'fontWeight': 'bold'}),
            dcc.Dropdown(
                id='category-filter',
                options=[{'label': 'All Categories', 'value': 'All'}] + 
                        [{'label': cat, 'value': cat} for cat in sorted(df['category'].unique())],
                value='All',
                style={'width': '300px', 'color': 'black'}
            )
        ], style={'display': 'inline-block', 'marginRight': '20px'}),
        
        html.Div([
            html.Label("Date Range:", style={'color': 'white', 'fontWeight': 'bold'}),
            dcc.DatePickerRange(
                id='date-filter',
                start_date=df['invoice_date'].min(),
                end_date=df['invoice_date'].max(),
                display_format='DD/MM/YYYY',
                style={'color': 'black'}
            )
        ], style={'display': 'inline-block'}),
        
    ], style={'padding': '20px', 'backgroundColor': '#1e1e1e', 'marginBottom': '20px'}),
    
    # KPI Cards
    html.Div([
        html.Div([
            html.Div([
                html.H4("💰 Total Revenue", style={'color': '#00d4ff'}),
                html.H2(id='kpi-revenue', children=f"${total_revenue:,.0f}", 
                        style={'color': 'white'})
            ], className='kpi-card', style={
                'backgroundColor': '#2d2d2d', 
                'padding': '20px', 
                'borderRadius': '10px',
                'textAlign': 'center',
                'width': '23%',
                'display': 'inline-block',
                'margin': '1%'
            }),
            
            html.Div([
                html.H4("👥 Total Customers", style={'color': '#00d4ff'}),
                html.H2(id='kpi-customers', children=f"{total_customers:,}", 
                        style={'color': 'white'})
            ], className='kpi-card', style={
                'backgroundColor': '#2d2d2d', 
                'padding': '20px', 
                'borderRadius': '10px',
                'textAlign': 'center',
                'width': '23%',
                'display': 'inline-block',
                'margin': '1%'
            }),
            
            html.Div([
                html.H4("🛒 Total Orders", style={'color': '#00d4ff'}),
                html.H2(id='kpi-orders', children=f"{total_orders:,}", 
                        style={'color': 'white'})
            ], className='kpi-card', style={
                'backgroundColor': '#2d2d2d', 
                'padding': '20px', 
                'borderRadius': '10px',
                'textAlign': 'center',
                'width': '23%',
                'display': 'inline-block',
                'margin': '1%'
            }),
            
            html.Div([
                html.H4("📊 Avg Order Value", style={'color': '#00d4ff'}),
                html.H2(id='kpi-aov', children=f"${avg_order_value:,.2f}", 
                        style={'color': 'white'})
            ], className='kpi-card', style={
                'backgroundColor': '#2d2d2d', 
                'padding': '20px', 
                'borderRadius': '10px',
                'textAlign': 'center',
                'width': '23%',
                'display': 'inline-block',
                'margin': '1%'
            }),
        ])
    ], style={'marginBottom': '30px'}),
    
    # Charts Row 1
    html.Div([
        html.Div([
            dcc.Graph(id='revenue-trend')
        ], style={'width': '48%', 'display': 'inline-block', 'padding': '10px'}),
        
        html.Div([
            dcc.Graph(id='category-chart')
        ], style={'width': '48%', 'display': 'inline-block', 'padding': '10px'}),
    ]),
    
    # Charts Row 2
    html.Div([
        html.Div([
            dcc.Graph(id='mall-chart')
        ], style={'width': '48%', 'display': 'inline-block', 'padding': '10px'}),
        
        html.Div([
            dcc.Graph(id='gender-chart')
        ], style={'width': '48%', 'display': 'inline-block', 'padding': '10px'}),
    ]),
    
], style={'backgroundColor': '#1a1a1a', 'padding': '20px'})

# Callbacks for interactivity
@app.callback(
    [Output('kpi-revenue', 'children'),
     Output('kpi-customers', 'children'),
     Output('kpi-orders', 'children'),
     Output('kpi-aov', 'children'),
     Output('revenue-trend', 'figure'),
     Output('category-chart', 'figure'),
     Output('mall-chart', 'figure'),
     Output('gender-chart', 'figure')],
    [Input('mall-filter', 'value'),
     Input('category-filter', 'value'),
     Input('date-filter', 'start_date'),
     Input('date-filter', 'end_date')]
)
def update_dashboard(selected_mall, selected_category, start_date, end_date):
    # Filter data
    filtered_df = df.copy()
    
    if selected_mall != 'All':
        filtered_df = filtered_df[filtered_df['shopping_mall'] == selected_mall]
    
    if selected_category != 'All':
        filtered_df = filtered_df[filtered_df['category'] == selected_category]
    
    if start_date and end_date:
        filtered_df = filtered_df[
            (filtered_df['invoice_date'] >= start_date) & 
            (filtered_df['invoice_date'] <= end_date)
        ]
    
    # Calculate KPIs
    kpi_revenue = f"${filtered_df['total_revenue'].sum():,.0f}"
    kpi_customers = f"{filtered_df['customer_id'].nunique():,}"
    kpi_orders = f"{filtered_df['invoice_no'].nunique():,}"
    kpi_aov = f"${filtered_df.groupby('invoice_no')['total_revenue'].sum().mean():,.2f}"
    
    # Revenue Trend
    monthly_data = filtered_df.groupby('year_month')['total_revenue'].sum().reset_index()
    fig_trend = px.line(monthly_data, x='year_month', y='total_revenue',
                        title='📈 Revenue Trend Over Time',
                        template='plotly_dark')
    fig_trend.update_traces(line_color='cyan', line_width=3, mode='lines+markers')
    fig_trend.update_xaxes(title_text='Month')
    fig_trend.update_yaxes(title_text='Revenue ($)')
    
    # Category Revenue
    cat_data = filtered_df.groupby('category')['total_revenue'].sum().reset_index()
    cat_data = cat_data.sort_values('total_revenue', ascending=False)
    fig_category = px.bar(cat_data, x='category', y='total_revenue',
                          title='💼 Revenue by Category',
                          template='plotly_dark')
    fig_category.update_traces(marker_color='lightblue')
    
    # Mall Revenue
    mall_data = filtered_df.groupby('shopping_mall')['total_revenue'].sum().reset_index()
    mall_data = mall_data.sort_values('total_revenue', ascending=False).head(10)
    fig_mall = px.bar(mall_data, x='shopping_mall', y='total_revenue',
                      title='🏬 Top Malls by Revenue',
                      template='plotly_dark')
    fig_mall.update_traces(marker_color='orange')
    fig_mall.update_xaxes(tickangle=-45)
    
    # Gender Distribution
    gender_data = filtered_df.groupby('gender')['total_revenue'].sum().reset_index()
    fig_gender = px.pie(gender_data, values='total_revenue', names='gender',
                        title='👫 Revenue by Gender',
                        template='plotly_dark',
                        color_discrete_sequence=[ '#ff6b9d','#00d4ff'])
    
    return kpi_revenue, kpi_customers, kpi_orders, kpi_aov, fig_trend, fig_category, fig_mall, fig_gender

if __name__ == '__main__':
    app.run(debug=True, port=8051)

**check out this link after running the above cell : ([Link](http://127.0.0.1:8051/))**